name: Telegram Chat GUI
version: "0.1.1"
slug: telegram_chat_gui
description: Telegram Web client in the Home Assistant sidebar
url: https://github.com/wallajl/home-assistant/tree/main/addons/telegram-chat-gui
arch:
  - amd64
  - aarch64
startup: application
boot: auto
init: false
ingress: true
ingress_port: 8099
panel_icon: mdi:message-text-outline
panel_title: Telegram
ports: {}
ports_description: {}
options:
  telegram_url: https://web.telegram.org/k/
schema:
  telegram_url: str
