build_from:
  amd64: ghcr.io/home-assistant/amd64-base-debian:bookworm
  aarch64: ghcr.io/home-assistant/aarch64-base-debian:bookworm
labels:
  org.opencontainers.image.title: "Snapchat Chat GUI"
  org.opencontainers.image.description: "Snapchat Web in the Home Assistant sidebar"
  org.opencontainers.image.source: "https://github.com/wallajl/home-assistant"
