name: Discord Chat GUI
version: "0.1.0"
slug: discord_chat_gui
description: Discord Web client in the Home Assistant sidebar
url: https://github.com/wallajl/home-assistant/tree/main/addons/discord-chat-gui
arch:
  - amd64
  - aarch64
startup: application
boot: auto
init: false
ingress: true
ingress_port: 8099
panel_icon: mdi:discord
panel_title: Discord
ports: {}
ports_description: {}
options:
  discord_url: https://discord.com/app
schema:
  discord_url: str
